# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'characterGeneratorGui.ui'
#
# Created: Sat Jun  6 13:41:28 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import sys

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(QtGui.QMainWindow):
    def __init__(self):
        QtGui.QMainWindow.__init__(self)
        self.setupUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.strUpButton = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.strUpButton.sizePolicy().hasHeightForWidth())
        self.strUpButton.setSizePolicy(sizePolicy)
        self.strUpButton.setMaximumSize(QtCore.QSize(32, 32))
        self.strUpButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("UpArrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.strUpButton.setIcon(icon)
        self.strUpButton.setObjectName(_fromUtf8("strUpButton"))
        self.horizontalLayout.addWidget(self.strUpButton)
        self.dexUpButton = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dexUpButton.sizePolicy().hasHeightForWidth())
        self.dexUpButton.setSizePolicy(sizePolicy)
        self.dexUpButton.setMaximumSize(QtCore.QSize(32, 32))
        self.dexUpButton.setText(_fromUtf8(""))
        self.dexUpButton.setIcon(icon)
        self.dexUpButton.setObjectName(_fromUtf8("dexUpButton"))
        self.horizontalLayout.addWidget(self.dexUpButton)
        self.conUpButton = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.conUpButton.sizePolicy().hasHeightForWidth())
        self.conUpButton.setSizePolicy(sizePolicy)
        self.conUpButton.setMaximumSize(QtCore.QSize(32, 32))
        self.conUpButton.setText(_fromUtf8(""))
        self.conUpButton.setIcon(icon)
        self.conUpButton.setObjectName(_fromUtf8("conUpButton"))
        self.horizontalLayout.addWidget(self.conUpButton)
        self.intUpButton = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intUpButton.sizePolicy().hasHeightForWidth())
        self.intUpButton.setSizePolicy(sizePolicy)
        self.intUpButton.setMaximumSize(QtCore.QSize(32, 32))
        self.intUpButton.setText(_fromUtf8(""))
        self.intUpButton.setIcon(icon)
        self.intUpButton.setObjectName(_fromUtf8("intUpButton"))
        self.horizontalLayout.addWidget(self.intUpButton)
        self.wisUpButton = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wisUpButton.sizePolicy().hasHeightForWidth())
        self.wisUpButton.setSizePolicy(sizePolicy)
        self.wisUpButton.setMaximumSize(QtCore.QSize(32, 32))
        self.wisUpButton.setText(_fromUtf8(""))
        self.wisUpButton.setIcon(icon)
        self.wisUpButton.setObjectName(_fromUtf8("wisUpButton"))
        self.horizontalLayout.addWidget(self.wisUpButton)
        self.chaUpButton = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chaUpButton.sizePolicy().hasHeightForWidth())
        self.chaUpButton.setSizePolicy(sizePolicy)
        self.chaUpButton.setMaximumSize(QtCore.QSize(32, 32))
        self.chaUpButton.setText(_fromUtf8(""))
        self.chaUpButton.setIcon(icon)
        self.chaUpButton.setObjectName(_fromUtf8("chaUpButton"))
        self.horizontalLayout.addWidget(self.chaUpButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lcdNumber = QtGui.QLCDNumber(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber.sizePolicy().hasHeightForWidth())
        self.lcdNumber.setSizePolicy(sizePolicy)
        self.lcdNumber.setMaximumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.horizontalLayout_2.addWidget(self.lcdNumber)
        self.lcdNumber_3 = QtGui.QLCDNumber(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_3.sizePolicy().hasHeightForWidth())
        self.lcdNumber_3.setSizePolicy(sizePolicy)
        self.lcdNumber_3.setMaximumSize(QtCore.QSize(32, 32))
        self.lcdNumber_3.setObjectName(_fromUtf8("lcdNumber_3"))
        self.horizontalLayout_2.addWidget(self.lcdNumber_3)
        self.lcdNumber_4 = QtGui.QLCDNumber(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_4.sizePolicy().hasHeightForWidth())
        self.lcdNumber_4.setSizePolicy(sizePolicy)
        self.lcdNumber_4.setMaximumSize(QtCore.QSize(32, 32))
        self.lcdNumber_4.setObjectName(_fromUtf8("lcdNumber_4"))
        self.horizontalLayout_2.addWidget(self.lcdNumber_4)
        self.lcdNumber_5 = QtGui.QLCDNumber(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_5.sizePolicy().hasHeightForWidth())
        self.lcdNumber_5.setSizePolicy(sizePolicy)
        self.lcdNumber_5.setMaximumSize(QtCore.QSize(32, 32))
        self.lcdNumber_5.setObjectName(_fromUtf8("lcdNumber_5"))
        self.horizontalLayout_2.addWidget(self.lcdNumber_5)
        self.lcdNumber_6 = QtGui.QLCDNumber(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_6.sizePolicy().hasHeightForWidth())
        self.lcdNumber_6.setSizePolicy(sizePolicy)
        self.lcdNumber_6.setMaximumSize(QtCore.QSize(32, 32))
        self.lcdNumber_6.setDigitCount(2)
        self.lcdNumber_6.setProperty("intValue", 19)
        self.lcdNumber_6.setObjectName(_fromUtf8("lcdNumber_6"))
        self.horizontalLayout_2.addWidget(self.lcdNumber_6)
        self.lcdNumber_2 = QtGui.QLCDNumber(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_2.sizePolicy().hasHeightForWidth())
        self.lcdNumber_2.setSizePolicy(sizePolicy)
        self.lcdNumber_2.setMaximumSize(QtCore.QSize(32, 32))
        self.lcdNumber_2.setNumDigits(2)
        self.lcdNumber_2.setProperty("intValue", 10)
        self.lcdNumber_2.setObjectName(_fromUtf8("lcdNumber_2"))
        self.horizontalLayout_2.addWidget(self.lcdNumber_2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2", None))



app = QtGui.QApplication(sys.argv)
ex = Ui_MainWindow()
ex.show()
sys.exit(app.exec_())
